name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24.x
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test:unit
